unpackaged/objects/Talent__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <label>Developer</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sales force</fullName>
                </value>
                <value>
                    <fullName>Java</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>None__c</fullName>
        <label>None</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Talent</label>
    <nameField>
        <label>Talent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Talents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ControllerClass.cls
public class ControllerClass {
   public List<Talent__c> myList{get;set;}
   public Talent__c mainobjType{get;set;}
   public ControllerClass(){
        myList= new List<Talent__c>();
        mainobjType=new Talent__c();
        myList=[select Name__c,Developer__c,None__c,Email__c from Talent__c where Email__c Like '%gmail.com%'];
    }
    Public void save(){
        List<Talent__c> myList= new List<Talent__c>();
        mainobjType=new Talent__c();
        myList=[select Name__c,Developer__c,None__c,	Email__c from Talent__c  where Email__c Like '%gmail.com%'];
       update myList;
    }
   
        
        
        
    }