unpackaged/objects/TestContact__c.object
<CustomObject>
    <fields>
        <fullName>CreatingDate__c</fullName>
        <label>CreatingDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>PhoneNumber</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>First</fullName>
                </value>
                <value>
                    <fullName>Second</fullName>
                </value>
                <value>
                    <fullName>Third</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TestContact</label>
    <nameField>
        <label>TestContact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestContact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testContactController.cls
public class testContactController {
     public TestContact__c ac{ get; set; }
     	public List<TestContact__c> samepage { get; set; }
    public testContactController(){
       //samepage= [select id,Name__c,PhoneNumber__c,Type__c,CreatingDate__c from TestContact__c order by createddate desc];
      
    }
    
    public PageReference save() {
       insert ac;  
      samepage= [select id,Name__c,PhoneNumber__c,Type__c,CreatingDate__c from TestContact__c order by createddate desc];
      
        return null;
    }
    Public PageReference back(){
        PageReference pr= new PageReference('/apex/talentpage');
        pr.setRedirect(true);
        return pr;
        
        
        
    }
}